import sys
import os.path

import numpy as np
import pandas as pd
import surrogate_factory as sf

## Import core libraries package for the simulation tool



@sf.node
def batch_extract(workflow, input_table=None):
    """_summary_
    This function will execute the Extract of the data generated by the simulation tool.
    it's dependant on the specific case depending on the output generated.
    Args:
        flow_variables (_type_): flow_variables
        input_table (_type_): input data

    Returns:
        _type_: parsed data from sim tool. pd.DataFrame
    """

    ## option with path to file in metadata as csv file
    metadata = workflow.get_step()
    path = metadata['path']
    
    dataset = pd.read_csv(path)
    ## example of data filtering
    # if 'MAT_filter' in metadata.keys():
        # MAT_filter = metadata['MAT_filter']
        # dataset = dataset[dataset["MAT_filter"] == MAT_filter]
    return dataset
    
    ## option with path to file in config as csv file. in case pipeline is initialized with --data [PATH]
    # file_path = workflow.config['input_data']
    # data_set = pd.read_csv(file_path)

    # return data_set


@sf.node
def batch_transform(workflow, parsed_batches):
    """_summary_
    Transform data if needed of the parsed data.
    Typical cases: columns renaming, merge/split fields, ...
    Args:
        flow_variables (_type_): flow_variables
        parsed_batches (_type_): parsed data (in batch optionally)

    Returns:
        _type_: data transformed. pd.DataFrame
    """
    

    return parsed_batches


@sf.node
def batch_load(workflow, transformed_batches, input_table=None):
    """_summary_
    merge input_table with transformed_batches
    Args:
        flow_variables (_type_): flow_variables
        transformed_batches (_type_): transformed data
        input_table (_type_): DoE generated with the inputs

    Returns:
        _type_: dataset. pd.DataFrame
    """

    return transformed_batches



@sf.node
def data_visualization(workflow, input_table):


    
    try:
        config = workflow.get_step()
        method = workflow.catalog.get_method("profiling_report")
        method(input_table, "Data Raw")
    except:
        print("No data")
        pass


    

